# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DEMDrainageAnalyses
                                 A QGIS plugin
 This plugin performs specific DEM analyses on drainage sites.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-07-01
        copyright            : (C) 2020 by FALASY Anamelechi
        email                : fvw.services@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DEMDrainageAnalyses class from file DEMDrainageAnalyses.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .DEM_drainage_analyses import DEMDrainageAnalyses
    return DEMDrainageAnalyses(iface)
